### ISSUE TITLE
Keep getting UnicodeDecodeError

### ISSUE THREAD

**Issue by HAlafeefi** [fa0311/twitter_openapi_python#14]
Hello,

Great Project, But when I try to use :
TwitterOpenapiPython().get_guest_client().get_default_api().get_tweet_result_by_rest_id(tweet_id)

Im getting "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe4 in position 4: invalid continuation byte" on some tweets for example this tweet "1729551862360109567"

Thanks,

**Comment by fa0311** [comment]
I too am aware of this problem, but can't figure out the cause.
It works fine with Node.js Fetch.

**Comment by fa0311** [comment]
I tried it and it seems to work now.
I don't know what is causing it :(

```py
from twitter_openapi_python import TwitterOpenapiPython

client = TwitterOpenapiPython().get_guest_client()
id = "1729551862360109567"
res = client.get_default_api().get_tweet_result_by_rest_id(id)
print(res)
```

**Comment by HAlafeefi** [comment]
Yup, same problem keeps happening, I tried to find the problem but im not that expert in python as I thought I was lol.

**Comment by fa0311** [comment]
It was caused by `urllib`.
`urllib` will not decompress gzip.

I have tentatively taken care of removing gzip from accept-encoding
Note that web clients (mainly Google chrome) include gzip in accept-encoding.
In the future, I will try to add support for requests to the OpenAPI-generator, so I will do my best to get this resolved.
